Proj_Metadata/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Offers_Accepted__c</fullName>
        <description>This is the current number of offers/units that have been accepted by this Contact.</description>
        <inlineHelpText>This is the current number of offers/units that have been accepted by this Contact.</inlineHelpText>
        <label>Offers Accepted</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
</CustomObject>

Proj_Metadata/objects/Offer__c.object
<CustomObject>
    <fields>
        <fullName>Acceptances__c</fullName>
        <defaultValue>0</defaultValue>
        <description>This is the current number of offers/units that have been accepted by customers.</description>
        <inlineHelpText>This is the current number of offers/units that have been accepted by customers.</inlineHelpText>
        <label>Acceptances</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Current_Units_Available__c</fullName>
        <description>This is the number of units of the offer that are currently available.</description>
        <inlineHelpText>This is the number of units of the offer that are currently available.</inlineHelpText>
        <label>Current Units Available</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <description>This is a description of the offer (ie. Organic Strawberries)</description>
        <inlineHelpText>This is a description of the offer (ie. Organic Strawberries)</inlineHelpText>
        <label>Description</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Original_Units_Available__c</fullName>
        <description>This is the maximum units available for this offer. This is entered when the offer is setup initially to represent the units in inventory.</description>
        <inlineHelpText>This is the maximum units available for this offer. This is entered when the offer is setup initially to represent the units in inventory.</inlineHelpText>
        <label>Original Units Available</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Offer</label>
    <nameField>
        <displayFormat>O-{00000000}</displayFormat>
        <label>Offer ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Offers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Proj_Metadata/objects/Offer_Acceptance__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>Offer_Results</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Offer__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Offer</label>
        <referenceTo>Offer__c</referenceTo>
        <relationshipName>Offer_Results</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Offer Acceptance</label>
    <nameField>
        <displayFormat>OA-{00000000}</displayFormat>
        <label>Offer Acceptance ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Offer Acceptances</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Proj_Metadata/classes/TestAcceptOfferUpdateCounts_trg.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an organization are executed whenever Apex code is deployed
 * to a production organization to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production organization. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the organization size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
@isTest
private class TestAcceptOfferUpdateCounts_trg {

    static testMethod void myUnitTest() {
        
        Account a = new Account();
        a.name = 'Test Method Account';
        insert a;
        
        Contact c = new Contact();
        c.firstName = 'Test';
        c.lastName = 'Method ';
        c.accountid = a.id;
        insert c;
        
        
        Offer__c offer = new Offer__c();
        offer.description__c = 'Test Method Offer';
        offer.original_units_available__c = 50;
        
        insert offer;
        
        Offer_Acceptance__c acceptance = new Offer_Acceptance__c();
        acceptance.offer__c = offer.id;
        acceptance.contact__c = c.id;
        
        insert acceptance;
        
        
        
        offer = [select id,current_units_available__c,acceptances__c from Offer__c where id=:offer.id limit 1];
        
        Test.startTest();
        
        
        System.assertEquals(offer.acceptances__c, 1);
        
        c = [select id,offers_accepted__c from Contact where id=:c.id limit 1];
        
        System.assertEquals(1,c.offers_accepted__c);
        
        offer = [select id,current_units_available__c from Offer__c where id=:offer.id limit 1];
        
        System.assertEquals(49,offer.current_units_available__c);
        
        
        delete acceptance;
        
        c = [select id,offers_accepted__c from Contact where id=:c.id limit 1];
        
        System.assertEquals(0,c.offers_accepted__c);
        
        
        offer = [select id,current_units_available__c from Offer__c where id=:offer.id limit 1];
        
        System.assertEquals(50,offer.current_units_available__c);
        
        Test.StopTest();
        
        
        
    }
}